TechStockWeb/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechStockWeb.Data;
using TechStockWeb.Models;

namespace TechStockWeb.Controllers
{
    public class ProductsController : Controller
    {
        private readonly TechStockContext _context;

        public ProductsController(TechStockContext context)
        {
            _context = context;
        }

        
        public async Task<IActionResult> Index(string SearchName, string SearchSerialNumber, string SearchType, string SearchSupplier, string SearchUser)
        {
            
            var products = _context.Products
                .Include(p => p.Supplier)
                .Include(p => p.TypeArticle)
                .AsQueryable();

            
            if (!string.IsNullOrEmpty(SearchName))
            {
                products = products.Where(p => p.Name.Contains(SearchName));
            }

            if (!string.IsNullOrEmpty(SearchSerialNumber))
            {
                products = products.Where(p => p.SerialNumber.Contains(SearchSerialNumber));
            }

            if (!string.IsNullOrEmpty(SearchType))
            {
                int typeId;
                if (int.TryParse(SearchType, out typeId)) 
                {
                    products = products.Where(p => p.TypeId == typeId);
                }
                else
                {
                    
                    products = products.Where(p => p.TypeArticle.Name.Contains(SearchType));
                }
            }

            if (!string.IsNullOrEmpty(SearchSupplier))
            {
                int supplierId;
                if (int.TryParse(SearchSupplier, out supplierId)) 
                {
                    products = products.Where(p => p.SupplierId == supplierId);
                }
                else
                {
                    
                    products = products.Where(p => p.Supplier.Name.Contains(SearchSupplier));
                }
            }

            if (!string.IsNullOrEmpty(SearchUser))
            {
                if (SearchUser == "NotAssigned")
                {
                    
                    products = from p in products
                               join m in _context.MaterialManagement on p.Id equals m.ProductId into assignments
                               from assignment in assignments.DefaultIfEmpty()
                               where assignment == null
                               select p;
                }
                else
                {
                    var userId = SearchUser;
                    products = from p in products
                               join m in _context.MaterialManagement on p.Id equals m.ProductId into assignments
                               from assignment in assignments.DefaultIfEmpty()
                               where assignment != null && assignment.UserId == userId
                               select p;
                }
            }


            
            var materialAssignments = await _context.MaterialManagement
                .Include(m => m.User)
                .ToListAsync();

            
            ViewBag.Users = new SelectList(await _context.Users.ToListAsync(), "Id", "UserName");

            ViewBag.MaterialAssignments = materialAssignments;

            
            ViewData["SearchName"] = SearchName;
            ViewData["SearchSerialNumber"] = SearchSerialNumber;
            ViewData["SearchType"] = SearchType;
            ViewData["SearchSupplier"] = SearchSupplier;
            ViewData["SearchUser"] = SearchUser; 

           
            ViewBag.TypeList = new SelectList(_context.TypeArticle, "Id", "Name");
            ViewBag.SupplierList = new SelectList(_context.Supplier, "Id", "Name");

            return View(await products.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Supplier)
                .Include(p => p.TypeArticle)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        
        public IActionResult Create()
        {
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "Name");
            ViewData["TypeId"] = new SelectList(_context.TypeArticle, "Id", "Name");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,SerialNumber,TypeId,SupplierId")] Product product)
        {
            Debug.WriteLine("Méthode Create appelée");
            Debug.WriteLine("Nom: "+ product.Name);
            Debug.WriteLine("SerialNumber: " + product.SerialNumber);
            Debug.WriteLine("TypeID: " + product.TypeId);
            Debug.WriteLine("SupplierID: " + product.SupplierId);
            Debug.WriteLine("ID : " + product.Id);
            var typeArticle = await _context.TypeArticle.FindAsync(product.TypeId);
            var supplier = await _context.Supplier.FindAsync(product.SupplierId);

            product.TypeArticle = typeArticle;
            product.Supplier = supplier;

            ModelState.Remove("TypeArticle");
            ModelState.Remove("Supplier"); 
            
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
 
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "Name", product.SupplierId);
            ViewData["TypeId"] = new SelectList(_context.TypeArticle, "Id", "Name", product.TypeId);
            return View(product);
        }

        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "Name", product.SupplierId);
            ViewData["TypeId"] = new SelectList(_context.TypeArticle, "Id", "Name", product.TypeId);
            return View(product);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,SerialNumber,TypeId,SupplierId")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            
            var typeArticle = await _context.TypeArticle.FindAsync(product.TypeId);
            var supplier = await _context.Supplier.FindAsync(product.SupplierId);

            
            product.TypeArticle = typeArticle;
            product.Supplier = supplier;

            
            ModelState.Remove("TypeArticle");
            ModelState.Remove("Supplier");

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "Name", product.SupplierId);
            ViewData["TypeId"] = new SelectList(_context.TypeArticle, "Id", "Name", product.TypeId);
            return View(product);
        }


        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Supplier)
                .Include(p => p.TypeArticle)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignToUser(int id, int userId)
        {
            var product = await _context.Products.FindAsync(id);
            var user = await _context.Users.FindAsync(userId);

            Debug.WriteLine(userId);
            if (product == null || user == null)
            {
                return NotFound();
            }

            
            var existingAssignment = await _context.MaterialManagement
                .FirstOrDefaultAsync(m => m.ProductId == id);

            if (existingAssignment != null)
            {

TechStockWeb/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechStockWeb.Data;
using TechStockWeb.Models;

namespace TechStockWeb.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly TechStockContext _context;

        public SuppliersController(TechStockContext context)
        {
            _context = context;
        }

        // GET: Suppliers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Supplier.ToListAsync());
        }

        // GET: Suppliers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier
                .FirstOrDefaultAsync(m => m.Id == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // GET: Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier.FindAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Supplier supplier)
        {
            if (id != supplier.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier
                .FirstOrDefaultAsync(m => m.Id == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var supplier = await _context.Supplier.FindAsync(id);
            if (supplier != null)
            {
                _context.Supplier.Remove(supplier);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SupplierExists(int id)
        {
            return _context.Supplier.Any(e => e.Id == id);
        }
    }
}

TechStockWeb/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechStockWeb.Data;
using TechStockWeb.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TechStockWeb.Areas.Identity.Data;

[Authorize(Roles = "Admin")] 
public class UsersController : Controller
{
    private readonly UserManager<TechStockWebUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;

    public UsersController(UserManager<TechStockWebUser> userManager, RoleManager<IdentityRole> roleManager)
    {
        _userManager = userManager;
        _roleManager = roleManager;
    }

    
    public async Task<IActionResult> Index()
    {
        var users = await _userManager.Users.ToListAsync();
        var userRoles = new List<UserRolesViewModel>();

        foreach (var user in users)
        {
            var roles = await _userManager.GetRolesAsync(user);
            userRoles.Add(new UserRolesViewModel { UserName = user.UserName, Roles = roles.ToList() });
        }

        return View(userRoles);
    }

    
    [HttpGet]
    public async Task<IActionResult> ManageRoles(string userName)
    {
        var user = await _userManager.FindByNameAsync(userName);
        if (user == null) return NotFound();

        var model = new UserRolesViewModel
        {
            UserName = user.UserName,
            Roles = (await _userManager.GetRolesAsync(user)).ToList()
        };

        ViewBag.AllRoles = new MultiSelectList(await _roleManager.Roles.ToListAsync(), "Name", "Name", model.Roles);

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> ManageRoles(UserRolesViewModel model)
    {
        var user = await _userManager.FindByNameAsync(model.UserName);
        if (user == null) return NotFound();

        var currentRoles = await _userManager.GetRolesAsync(user);
        await _userManager.RemoveFromRolesAsync(user, currentRoles);

        if (model.Roles != null)
            await _userManager.AddToRolesAsync(user, model.Roles);

        return RedirectToAction("Index");
    }
}

TechStockWeb/Views/Shared/_LanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization
@using System.Globalization
@using TechStockWeb.Models

@{
    var cultureFeature = Context.Features.Get<IRequestCultureFeature>();
    string languageId = cultureFeature?.RequestCulture.UICulture.TwoLetterISOLanguageName ?? "en";
    string languageName = Language.LanguageDictionary.ContainsKey(languageId)
        ? Language.LanguageDictionary[languageId].Name
        : "English";
    var thisPage = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<!-- _LanguagePartial.cshtml -->
<ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            🌍 @CultureInfo.CurrentCulture.Name
        </a>
        <ul class="dropdown-menu" aria-labelledby="languageDropdown">
            @foreach (var lang in Language.Languages)
            {
                <li>
                    <form method="post" asp-controller="Home" asp-action="ChangeLanguage" class="d-inline">
                        <input type="hidden" name="culture" value="@lang.Id" />
                        <input type="hidden" name="returnUrl" value="@Context.Request.Path" />
                        <button type="submit" class="dropdown-item">@lang.Name</button>
                    </form>
                </li>
            }
        </ul>
    </li>
</ul>

TechStockWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Localization
@using System.Globalization
@using TechStockWeb.Resources

@inject IStringLocalizer<SharedResource> _localizer
@inject IStringLocalizer<SharedResource> StringLocalizer

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechStockWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TechStockWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-house-door"></i> TechStockWeb
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin") || User.IsInRole("Support"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                    <i class="bi bi-house"></i> @Localizer["Home"]
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">
                                    <i class="bi bi-shield-lock"></i> @Localizer["Privacy"]
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">
                                    <i class="bi bi-box-seam"></i> @Localizer["Products"]
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TypeArticles" asp-action="Index">
                                    <i class=" bi bi-laptop"></i> @Localizer["TypeArticles"]
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Suppliers" asp-action="Index">
                                    <i class="bi bi-truck"></i> @Localizer["Suppliers"]
                                </a>
                            </li>
                          
                        }
                        @if (User.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="MaterialManagements" asp-action="MyAssignedProducts">
                                    <i class="bi bi-clipboard-check"></i> @Localizer["My Assigned Products"]
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">
                                    <i class="bi bi-people"></i> @Localizer["Users"]
                                </a>
                            </li>
                        }
                    </ul>

                    <partial name="_LoginPartial" />
                    <partial name="_LanguagePartial" />

                </div>
            </div>
        </nav>

        <div class="container">
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - TechStockWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        document.getElementById('languageSelect').addEventListener('change', function () {
            let selectedLang = this.value;
            let currentLang = "@CultureInfo.CurrentCulture.Name";

            if (selectedLang !== currentLang) {
                document.getElementById('languageForm').submit();
            }
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>